# Generated by Django 5.2.1 on 2025-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ano_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meta_doacoes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
